### ISSUE TITLE
[UART] Move device parameters such as device (i.e., "/dev/ttyUSB0") and baudRate (i.e., 9600) to res/devices/sample-devices.yaml

### ISSUE THREAD

**Issue by vediyappan-hcl** [edgexfoundry/device-uart#15]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
UART device service
This feature request is to move the device parameters from res/profiles/sample-profile.yaml to res/devices/sample-devices.yaml

### Description [**REQUIRED**]
UART device service contains pre-defined devices in res/devices/devices.yaml file. Generally, the device profile describes a type of device within the EdgeX system. Each device managed by a device service has an association with a device profile, which defines that device type in terms of the operations which it supports.

Currently the device parameters device (i.e., /dev/ttyUSB0) and baudRate (i.e., 9600) presents in res/profiles/generic.yaml file. Can the parameters device (dev) and baud rate (baud) moved to res/devices/devices.yaml file?

### Describe the solution you'd like
Move device parameters such as device (dev) and baud rate (baud) to res/devices/devices.yaml.

For example:

```
deviceList:
  name: sample-uart-device
  profile-name: sample-uart-profile
  protocols:
	UART:
	  device: "/dev/ttyUSB0"
	  baudRate: 9600
```

### Describe alternatives you've considered
N/A
